import type { Metadata } from "next";
import "./globals.css";
import { Spinnaker } from "next/font/google";
import Cursor from "./_components/main/Cursor";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontFamily = Spinnaker({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${fontFamily.className} antialiased`}>
        <Cursor />
        {children}
      </body>
    </html>
  );
}
